#!/bin/bash      
#title           :
#description     :
#author		     :Simon Peter Mendy

echo "SHELL is: " $SHELL
echo "BASH_VERSION is: " $BASH_VERSION
echo 'HISTSIZE is: '$HISTSIZE
echo 'SSH_CLIENT is: '$SSH_CLIENT
